Test: CheckMisa
Target: verilator_target
Waiting for OpenOCD to start up...
-------------------------[ /tmp/openocddv_tu6h8.log ]-------------------------
+  USE_FREERTOS=0 openocd -f targets/RISC-V/dm_debug.cfg
Open On-Chip Debugger 0.12.0+dev-01897-gf5dd564a7 (2025-03-11-08:50)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
Info : Initializing remote_bitbang driver
Info : Connecting to localhost:9999
Info : remote_bitbang driver initialized
Info : Note: The adapter "remote_bitbang" doesn't support configurable speed
Info : JTAG tap: riscv.cpu tap/device found: 0x249511c3 (mfg: 0x0e1 (Wintec Industries), part: 0x4951, ver: 0x2)
Info : datacount=2 progbufsize=8
Info : Examined RISC-V core; found 1 harts
Info :  hart 0: XLEN=32, misa=0x40001104
Info : [riscv.cpu] Examination succeed
Info : [riscv.cpu] starting gdb server on 3333
Info : Listening on port 3333 for gdb connections
Error: couldn't bind tcl to socket on port 6666: Address already in use
Info : remote_bitbang interface quit
TAP: riscv.cpu


--------------------------------[ Traceback ]---------------------------------
Traceback (most recent call last):
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1389, in run
    self.classSetup()
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1445, in classSetup
    BaseTest.classSetup(self)
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1352, in classSetup
    self.target_process = self.target.create()
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/targets/RISC-V/verilator_target.py", line 38, in create
    return testlib.Openocd(server_cmd=f"openocd -f {self.openocd_config_path}")
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 378, in __init__
    self.start(cmd, logfile, extra_env)
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 404, in start
    m = self.expect(
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 491, in expect
    raise TestLibError("OpenOCD exited early.")
testlib.TestLibError: OpenOCD exited early.
-------------------------------[ End of logs ]--------------------------------
Result: exception
Logfile: logs/20250603-115135-verilator_target-CheckMisa.log
Reproduce: ./gdbserver.py targets/RISC-V/verilator_target.py CheckMisa
Time elapsed: 3.41s
