Test: CheckMisa
Target: verilator_target
Waiting for OpenOCD to start up...
-------------------------[ /tmp/openocdnd3ck_rh.log ]-------------------------
+ REMOTE_BITBANG_HOST=localhost REMOTE_BITBANG_PORT=9999 USE_FREERTOS=0 openocd -f targets/RISC-V/dm_debug.cfg
Open On-Chip Debugger 0.12.0+dev-01897-gf5dd564a7 (2025-03-11-08:50)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

--------------------------------[ Traceback ]---------------------------------
Traceback (most recent call last):
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1389, in run
    self.classSetup()
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1445, in classSetup
    BaseTest.classSetup(self)
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1352, in classSetup
    self.target_process = self.target.create()
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/targets/RISC-V/verilator_target.py", line 57, in create
    return testlib.Openocd(
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 378, in __init__
    self.start(cmd, logfile, extra_env)
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 404, in start
    m = self.expect(
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 498, in expect
    raise TestLibError(f"Timed out waiting for {regex} in "
testlib.TestLibError: Timed out waiting for b'Listening on port (?P<port>\\d+) for (?P<server>(?:gdb)|(?:tcl)) connections' in /tmp/openocdnd3ck_rh.log
-------------------------------[ End of logs ]--------------------------------
Result: exception
Logfile: logs/20250603-143632-verilator_target-CheckMisa.log
Reproduce: ./gdbserver.py targets/RISC-V/verilator_target.py CheckMisa
Time elapsed: 60.05s
